### ISSUE TITLE
openldap - livenessProbe may fail if ldapsearch is expected to return more than 500 objects

### ISSUE THREAD

**Issue by pmauduit** [camptocamp/helm-georchestra#2]
See here:
https://github.com/camptocamp/helm-georchestra/blob/main/templates/openldap-deployment.yaml#L46-L52

Quick fix / workaround: limit the search to the ou=roles branch of the LDAP, where it is very unlikely to have more than 15 objects.

It would also be possible to do the search being connected as admin, but I'm not sure we have access to the env variables containing the necessary secrets in the livenessProbe.

**Comment by fvanderbiest** [comment]
What about using the same as upstream ?
https://github.com/georchestra/georchestra/blob/7544689c4121910f9c7312495b40aaf9b046e50f/ldap/Dockerfile#L34

**Comment by pmauduit** [comment]
why not ...

**Comment by pmauduit** [comment]
we are now querying for the cn=admin (which basically does the same as the docker healthcheck upstream):
https://github.com/camptocamp/helm-georchestra/blob/main/templates/openldap-deployment.yaml#L57
